### ISSUE TITLE
because network issue it is impossible for me to try this project please see below error

### ISSUE THREAD

**Issue by gaowayne** [wpdk/wpdk#1]
Could you please put all the deps on the github that can be access by all the world without any authentication?

```
C:\Wayne\code\winspdk>curl -LJO https://raw.githubusercontent.com/wpdk/wpdk/master/scripts/pkgdep.bat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:24 --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Timed out

C:\Wayne\code\winspdk>curl -LJO https://raw.githubusercontent.com/wpdk/wpdk/master/scripts/pkgdep.bat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Timed out

C:\Wayne\code\winspdk>ping raw.githubusercontent.com

Pinging raw.githubusercontent.com [151.101.108.133] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
```

**Comment by nconnolly1** [comment]
Hi @gaowayne - this looks like an issue with your network / firewall / gateway.

All of the dependencies are part of a public repo and no authentication is required. I've just tested this by starting a Windows Sandbox (which won't have any GitHub credentials) and I've run the same curl command without issue. I've also run 'ping raw.githubusercontent.com' and it works for me.

If you can't get curl to work for you, just download scripts/pkgdep.bat from the WPDK GitHub repo and then execute it.

However, if you have network issues, you may also have difficulties downloading the required packages when you run pkgdep.bat.

Hope this helps.

**Comment by gaowayne** [comment]
@nconnolly1 yes, man, I am from China, it is almost impossible for me to fix these network issue. if you can put all things into just github, it may be great.

**Comment by nconnolly1** [comment]
Hi @gaowayne - the good news is that all of the files **_are_** hosted in github and are part of the wpdk/wpdk repo.

It sounds as though raw.githubusercontent.com (a github site) is being blocked where you are.

I would suggest that you browse to https://github.com/wpdk/wpdk/blob/master/scripts/pkgdep.bat and cut and paste the contents into a local file.
