### ISSUE TITLE
Error when building SPDK for windows

### ISSUE THREAD

**Issue by ChaithraMahadeva** [wpdk/wpdk#2]
Hi, 

I'm trying to use SPDK for windows and followed the user guide to build WPDK and SPDK for windows from Linux environment and the MinGW cross compiler. Below are last few lines of the log with error I'm getting in last step while running "make -j8" command (https://github.com/wpdk/wpdk/blob/master/doc/build-spdk.md#build-spdk).

  LIB libspdk_ut_mock.a
  CC lib/iscsi/conn.o
  CC lib/iscsi/init_grp.o
  CC lib/iscsi/iscsi.o
In file included from iscsi.c:47:
/home/user/spdk/lib/iscsi/md5.h:41:10: fatal error: openssl/evp.h: No such file or directory
   41 | #include <openssl/evp.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/user/spdk/mk/spdk.common.mk:465: iscsi.o] Error 1
make[1]: *** [/home/user/spdk/mk/spdk.subdirs.mk:44: iscsi] Error 2
make: *** [/home/user/spdk/mk/spdk.subdirs.mk:44: lib] Error 2

Kindly check and let me know if I'm missing anything. Thank you for your time.

Regards,
Chaithra

**Comment by nconnolly1** [comment]
This would appear to be due to a recent change to SPDK. I'll take a look, but in the meantime I'd recommend checking out the v22.01 branch to verify your build environment.

**Comment by ChaithraMahadeva** [comment]
Hi @nconnolly1 ,

I'm sorry, I do not find the branch you are suggesting here https://github.com/wpdk/spdk/branches/all. Am I searching in the right place?. Would you kindly sharing me more details of the build version (spdk/wpdk).

Thank you.

**Comment by nconnolly1** [comment]
You can use tag v22.01 from the main SPDK repository, located here:
https://github.com/spdk/spdk/releases/tag/v22.01

**Comment by ChaithraMahadeva** [comment]
Hi @nconnolly1 ,

Thank you for the details. The build was successful with few warnings. I'm trying to run an example hello-world code from SPDK in windows to check the built API windows support. (https://github.com/spdk/spdk/blob/master/examples/nvme/hello_world/hello_world.c)

Can I directly use the code and the built SPDK API in the windows to test? or Do I need to make some initial configuration or code changes? Kindly advice.

Thank you.

**Comment by nconnolly1** [comment]
I haven't used the hello_world example code, so can't really advise you on it. As far as I can see, it is expecting to enumerate the NVMe controllers on the current system and reports that non-Linux systems do not support this. If you have an existing NVMe-oF target, you may be able to use the -r flag to connect to it, but I haven't tried it.

For getting started, I'd recommend the Prerequisites section in the README.md (https://github.com/wpdk/wpdk#runtime-prerequisites) and the following sections which describe how to run unit tests and some sample target stacks.

**Comment by nconnolly1** [comment]
With regard to the compilation warnings you saw: which version of mingw are you using? (run 'apt list gcc-mingw-w64' within WSL). The compilation should be warning free with 9.3.0.

**Comment by ChaithraMahadeva** [comment]
Hi @nconnolly1 ,

Thank you for your suggestion. 

I have another query regarding SPDK in WSL. I would like to know if SPDK (for Linux/windows) could be installed and used in WSL same as in Linux, because I understand that DPDK could not be used in WSL similar to Linux as few of the features could be missing. 

Please let me know if such implementation is possible if yes how can it be done and what will be the expected performance of SPDK APIs?

Thank you for your time.

Best regards,
Chaithra Mahadeva

**Comment by nconnolly1** [comment]
Hi Chaithra,

Apologies for the delayed response - I've been travelling.

The 'evp.h' issue you reported has now been fixed - SPDK usage of the md5 functions had changed recently. I'll close this issue.

With regard to your subsequent question about running SPDK in WSL - the best place for this type of query is probably the SPDK slack #windows channel - it's a more convenient way of holding a discussion and it's easier for others to join in and share their experience. There's a link to join at https://spdk.io/community/.

The question about WSL really depends upon what you want to do with SPDK and which version of WSL (1 or 2) you are considering using. WSL2 has a full Linux kernel and should be able to run the SPDK stack, however obtaining direct access to the hardware from WSL2 is likely to be more of an issue. I'd suggest posting the question to Slack with as much detail about your intended usage as you can provide (e.g. are you looking for target mode, initiator mode, direct access to NVMe queue pairs etc).
