### ISSUE TITLE
spdk_env_init: *ERROR*: Failed to initialize DPDK

### ISSUE THREAD

**Issue by wqlxx** [wpdk/wpdk#3]
I build the wpdk with spdk in ubuntu 2204 in wsl2. Then I copy the `bin` and `test` folder to windows OS.  But I got the following error message: 
> PS C:\share\bin> .\spdk_tgt.exe
[2023-06-25 04:02:07.562841] Starting SPDK v22.05.1-pre git sha1 d718608d3 / DPDK 22.03.0 initialization...
[2023-06-25 04:02:07.588890] [ DPDK EAL parameters: [2023-06-25 04:02:07.599023] spdk_tgt [2023-06-25 04:02:07.601957] --no-shconf [2023-06-25 04:02:07.687991] -c 0x1 [2023-06-25 04:02:07.690648] --huge-unlink [2023-06-25 04:02:07.693804] --log-level=lib.eal:6 [2023-06-25 04:02:07.697959] --log-level=lib.cryptodev:5 [2023-06-25 04:02:07.708355] --log-level=user1:6 [2023-06-25 04:02:07.712464] ]
EAL: Multi-process support is requested, but not available.
EAL: Cannot claim hugepage privilege
Verify that large-page support privilege is assigned to the current user
EAL: FATAL: Cannot get hugepage information
EAL: Cannot get hugepage information
[2023-06-25 04:02:07.733607] init.c: 611:spdk_env_init: *ERROR*: Failed to initialize DPDK
[2023-06-25 04:02:07.738569] app.c: 361:app_setup_env: *ERROR*: Unable to initialize SPDK env

I am confused how to run `iscsi_tgt.exe` or `spdk_tgt.exe` on windows. How to run the dpdk?

**Comment by nconnolly1** [comment]
I suspect you have missed the steps in the [Prerequisites](https://github.com/wpdk/wpdk#runtime-prerequisites) section of the main README. Specifically the reference to the DPDK documentation to enable 'lock pages in memory'. I would also suggest reading the following paragraph about the virt2phys driver or the alternative patch.

If you are asking for a large amount of memory and the system has been running for a while, it is sometimes necessary to reboot to get sufficient physically contiguous memory.

Regards,
Nick

**Comment by qiang-w-ruijie** [comment]
@nconnolly1 Thank you for your reminder, I reinstall windows OS, but forgot to modify it.

**Comment by nconnolly1** [comment]
Hi @wqlxx - I wouldn't recommend copying the 'test' folder to Windows - in order to run the automated tests, Python is used to configure SPDK. Unfortunately, Python on Windows does not currently support AF_UNIX sockets. So, the best way to run things is from WSL - that way you have a bash shell and a suitable version of Python. The executables are Windows executables and will automatically be run as Windows processes rather than running in WSL, but the test harness will be executing inside WSL.

**Comment by qiang-w-ruijie** [comment]
@nconnolly1 Thanks for your reply. I hope to use `iscsi_tgt.exe` to provide iscsi target service, cause windows hyperv server 2019 did not provide `FS-iSCSITarget-Server` module. So I hope `wpdk` with `iscsi_tgt.exe` can do it.
