### ISSUE TITLE
Redundant check and a skipped check

### ISSUE THREAD

**Issue by ganap-ram** [wpdk/wpdk#4]
https://github.com/wpdk/wpdk/blob/4d78798304ce176aee096ea245c26e99b0d0ee24/src/mman.c#L88

The above check seems to validate h's content. I suppose, this is a redundant check; and importantly, the intention is probably to check hMap.

This issue is being raised based on code review.

**Comment by nconnolly1** [comment]
Good find - thank you! This should indeed be:

`if (hMap == INVALID_HANDLE_VALUE) {`

I'll commit a fix later today. In future, please feel free to submit pull requests. There may be some teething issues, but your contribution is appreciated and we'll work with you to streamline the process.

**Comment by ganap-ram** [comment]
Sure, Thanks you for the quick acknoeledgement!

**Comment by nconnolly1** [comment]
It turns out the issue is more complex - CreateFileMapping returns NULL on failure.
