### ISSUE TITLE
The loop is not formed correctly.

### ISSUE THREAD

**Issue by ganap-ram** [wpdk/wpdk#5]
https://github.com/wpdk/wpdk/blob/4d78798304ce176aee096ea245c26e99b0d0ee24/src/signal.c#L198

It appears that, the idea of the loop is to go through the handles and free them. If so, the loop variable isn't handled correctly.

**Comment by nconnolly1** [comment]
Good find - thank you! This should be:

`while (n-- > 0)`

I'll commit a fix later today. In future, please feel free to submit pull requests as per the comment in issue #4.

**Comment by ganap-ram** [comment]
Thank you for acknowledging. Sure! For the next few weeks I might send some issues your way, as am limited by some logistics to fixing them by myself, but will eventually get there and start contributing here. Thanks!

**Comment by ganap-ram** [comment]
and in the above loop, I suppose n == 0 is also a valid entry. Thanks!

**Comment by nconnolly1** [comment]
n is the total number of handles that have been opened. All of the handles from 0 ... n-1 need to be closed, so as long as n is greater than zero there is still work to do. The smallest correct fix is to check if n is greater than zero and if it is, use the post-decremented value to close the handle.

Having said that, it's not my usual coding style, so I'll take a look and see if there was any reason it was done this way. I'd normally use the simpler:

`for (i = 0; i < n; i++)
  CloseHandle(h[i]);`

**Comment by nconnolly1** [comment]
Ah! I used a while loop because **i** is unsigned and **n** is signed which causes a compiler warning on some platforms.  Using a  cast or a different loop variable would avoid the issue, but the while loop was simpler.
